### ISSUE TITLE
Improvement on build script 

### ISSUE THREAD

**Issue by edwardt** [Vagabond/erlang-syslog#12]
Please improve or write instruction on building this module.
Ideally when compile riak, it will be nice to see it as one go rather than hunting down errors that are not contributing to try using Riak. Riak depends on erlang-syslog and when compiling it cannot find the erl_interface.h file, which I need to set it manually.
Is it possible to probe for it in the build script in future?

Error.
ompiling /opt/riak/deps/syslog/c_src/syslog_drv.c
/opt/riak/deps/syslog/c_src/syslog_drv.c:30:24: error: erl_driver.h: No such file or directory
/opt/riak/deps/syslog/c_src/syslog_drv.c:45: error: expected specifier-qualifier-list before ‘ErlDrvPort’
/opt/riak/deps/syslog/c_src/syslog_drv.c: In function ‘encode_error’:
/opt/riak/deps/syslog/c_src/syslog_drv.c:60: error: ‘ERL_DRV_ERROR_GENERAL’ undeclared (first use in this function)

**Comment by binarytemple-bet365** [comment]
Candidate for close?
