### ISSUE TITLE
Publish latest release to Hex

### ISSUE THREAD

**Issue by ddeboer** [Vagabond/erlang-syslog#30]
Currently, the latest release on GitHub is 1.0.5, but Hex only has 1.0.2.

At Zotonic, we came up with Hexpub, an easy way to keep your Hex packages up-to-date: https://github.com/zotonic/hexpub

Would you be okay with a PR to add Hexpub to erlang-syslog?

**Comment by Vagabond** [comment]
Please!

**Comment by slashmili** [comment]
@Vagabond any chance you can do it by hand?

I am maintaining `ex_syslogger` and really need `1.0.5` in hex to be able to publish my package(hex only allows dependencies that are in hex)    

If you don't have time, you may grant me access to publish `syslog` to hex

**Comment by Vagabond** [comment]
I've never published to hex. I don't know who has done it in the past and if they're the one who needs to grant permission, or if I can?

**Comment by slashmili** [comment]
I'm sure @ericmj can help us here.

**Comment by ericmj** [comment]
@Vagabond There is no current owner of the syslog package so if you send an email to support@hex.pm from your GitHub email including the username of your Hex.pm account we can give the ownership to you.

**Comment by slashmili** [comment]
@Vagabond could you also on that email, request to grant access to me as well? In future I can do the hard work for you!

My hex account is `slashmili`

**Comment by tsloughter** [comment]
@slashmili can you publish a new version based on master? Or give me permissions to?

**Comment by tsloughter** [comment]
Mind closing this issue now too?

**Comment by slashmili** [comment]
I'll leave it to @Vagabond. I can't close issues here
