### ISSUE TITLE
Don't use git protocol to download pc plugin

### ISSUE THREAD

**Issue by sixohsix** [Vagabond/erlang-syslog#35]
In the rebar config file the `pc` plugin section is written like this:

```
{plugins, [
  { pc, { git, "git://github.com/blt/port_compiler.git", {tag, "1.6.0"}}}
]}.
```

However, my employer's network blocks git connections. I've looked at other packages and they seem to always use `https` to fetch GitHub repos. So I think the plugins section should be changed like this so that it works on networks that are hostile to git connections:

```
{plugins, [
  { pc, { git, "https://github.com/blt/port_compiler.git", {tag, "1.6.0"}}}
]}.
```

After making this change locally I was able to compile the syslog package.

**Comment by djnym** [comment]
@sixohsix  You can override this in your rebar.config by adding this.
```erlang
{ overrides, [
  {override, syslog, [
    {plugins, [
      {pc, {git, "https://github.com/blt/port_compiler.git", {tag, "1.6.0"}}}
    ]}
  ]}
]}.
```
You can use this functionality in rebar3 to also do things like fork all your dependencies into your company github and override all deps to point to those.

**Comment by tsloughter** [comment]
It now uses the `pc` hex package so this issue can be closed.
